### ISSUE TITLE
Harmonic Balance

### ISSUE THREAD

**Issue by gogobers** [ra3xdh/qucs#13]
In earlier Version of Spice4Qucs variant of QUCS there used to be a Harmonic Balance simulation, that worked with XYCE (quite nicely for me). I have read there was an issue with XYCE and they wanted to change something. Anyway, the HB-Simulations gone in RC8, Any chance to get it back, or a chance I can help?
Thanks
Gerald
P.S.: Do not get me wrong: You did an absolutely great job! I appreciate the effort very much!

**Comment by ra3xdh** [comment]
It is not a bug. I haven't removed HB simulation. "Default simulator" setting was introduced a some time ago. Qucs hides simulator-incompatible components from the GUI now. You need to select XYCE as the default simulator and restart Qucs. HB will appear again. See this screenshot:
![qucs-hb](https://cloud.githubusercontent.com/assets/4920080/20699503/16607914-b621-11e6-8738-627a1bef70af.png)

**Comment by gogobers** [comment]
That makes my Day, Thank you!
