### ISSUE TITLE
Failure opening some examples that requires "Pac" component

### ISSUE THREAD

**Issue by cvgaviao** [ra3xdh/qucs#16]
I have installed QUCS-S 0.0.19 using a downloaded .deb file.
I tried to open filter_optimization.sch example file and then this error panel showed up:

![qucs-s_pac_error](https://cloud.githubusercontent.com/assets/251734/23436025/d7189eda-fde7-11e6-9fad-2f1c69b693b9.png)

**Comment by ra3xdh** [comment]
It is not a bug. AC source is one of SPICE-incompatible devices. It is Qucsator-only device. Such devices become locked if Ngspice is selected as default engine. You can simulate schematic with SPICE-incompatible components only with Qucsator (should be selected as default simulation kernel). Explained also here: https://github.com/Qucs/qucs/issues/77#issuecomment-60744725
