### ISSUE TITLE
Schematic duplicating doesn't change document settings

### ISSUE THREAD

**Issue by antage** [ra3xdh/qucs#26]
I tried to duplicate a schematic and I observe strange behavior. After simulation (with ngspice) I get a tab with plot and data from original schematic instead of plot and data from duplicated schematic.

The reason for this behavior is data set and data display filenames aren't changed after duplicating and reference to original schematic.

I think when we duplicate a schematic we should rename data set, data display and octave script filenames.

**Comment by ra3xdh** [comment]
Hi, Anton! What method of schematic duplication are you using? Don't copy schematic file. Use `SaveAs` command to make a copy of schematic.

**Comment by antage** [comment]
@ra3xdh 
I use context menu:

![duplicate](https://user-images.githubusercontent.com/1032/27515109-c80b8204-59a4-11e7-8f4c-eeae959d5633.png)

**Comment by ra3xdh** [comment]
Yes, there is a problem with duplication in mainline Qucs package. It may not work as expected. See also https://github.com/Qucs/qucs/issues/633 for details. Use `SaveAs` for schematic duplication and to bypass this featurebug.
