### ISSUE TITLE
Netlist lists subscircuit twice

### ISSUE THREAD

**Issue by ldpgh** [ra3xdh/qucs#5]
Xyce complains about subcircuit definition found twice (nand2 and inv1).

Attached the circuit hierarchy (.txt added for GitHub):
- [zt_vco.sch.txt](https://github.com/ra3xdh/qucs/files/514484/zt_vco.sch.txt) ... top level
- [inv1.sch.txt](https://github.com/ra3xdh/qucs/files/514486/inv1.sch.txt)
- [nand2.sch.txt](https://github.com/ra3xdh/qucs/files/514485/nand2.sch.txt)
- [vco.sch.txt](https://github.com/ra3xdh/qucs/files/514487/vco.sch.txt)

Btw. Ngspice & LTspice do not even throw out a warning with default settings.

**Comment by ra3xdh** [comment]
I can confirm this. Ngspice allows subcircuits to be included multiple times. But XYCE gives an error. I will add fix for this bug.

**Comment by ra3xdh** [comment]
This bug concerns only nested subcircuits. Single-level subcircuits are processed normally. I have just added a fix. Now nested subcircuits could be simulated with XYCE. See https://github.com/Qucs/qucs/commit/d055c9e38c8e3d36e5039d16b117d19a3b559dfe This fix will go into upcoming RC8.
