### ISSUE TITLE
Feature request: add selected simulator to the status line of the schematic window

### ISSUE THREAD

**Issue by ldpgh** [ra3xdh/qucs#6]
Is there a chance to have the selected simulator added to the status line of the schematic window next to the coordinates (bottom, right)?

**Comment by ra3xdh** [comment]
Yes, it's a good idea to add somewhere an indication of the default simulator. I think it will be possible.

**Comment by ra3xdh** [comment]
I have added indication for Default simulator by this commit: https://github.com/ra3xdh/qucs/commit/96ff46eee125cfe9aaa79f30d574b5165d18d0aa . See this screenshot:
![new_status](https://cloud.githubusercontent.com/assets/4920080/19835064/5489c1e0-9e94-11e6-9167-c29b2479d43e.png)
