### ISSUE TITLE
How to add MOSFET primitive for external model card

### ISSUE THREAD

**Issue by ldpgh** [ra3xdh/qucs#9]
I'd like to create/have 2 MOFSET-symbols (pFET, nFET) with parameters w,l,m,model ... maybe it could bee called "custom-component".

1) What is the right way to do it?
2) How can a corner-simulation be executed later on?

Adding the model card by spice-component seems not to be the right choice for a corner-simulation. I have no idea how to sweep the different model-cards (min, typ, max)

**Comment by ra3xdh** [comment]
What type of "custom component" did you mean? We have different components and simulations that may solve this issue:

* You may use special "SPICE" variance for transistors https://github.com/Qucs/qucs/issues/77#issuecomment-107031584 , etc. Such components allow to attach SPICE models and use full SPICE definition. All available models are supported (Lv.1-9, BSIM, etc.) And you may use `@model[param]` notation as Parameter Sweep variable. It allows to sweep model parameters. This will not work with universal devices. SPICE devices don't work with Qucsator. These devices are highlighted by dark-red. Have you tried these components? Here is inverter example with attached model library and MOSFET parameters (L and W).
![74hc](https://cloud.githubusercontent.com/assets/4920080/19482740/04b4d270-9563-11e6-85ee-6c5a35b8ddc7.png)
* There exists SPICE generic device "Z" component at "File components" tab. You can define SPICE letter and number of pins for it. This component is useful for devices that are already presented in simulation kernel but not yet added in GUI. I don't recommend to use this components for usual transistors. This example illustrates how to use it with MOSFET. 
![mos](https://cloud.githubusercontent.com/assets/4920080/19482296/bada8196-9561-11e6-878f-f0d8a291f9a0.png)
* If you want to use sweeping for more than two parameters simultaneously, you will be unable to do it with standard Par.Sweep. You need to use "Nutmeg Script" simulation for Ngspice. You can construct any non-standard simulation using this mode. See https://github.com/Qucs/qucs/issues/77#issuecomment-93783668 for short example. You can put any Nutmeg code into this simulation. The only limitation is  this code should produce valid raw-SPICE output. 
![cust_ex](https://cloud.githubusercontent.com/assets/4920080/19482516/60de9924-9562-11e6-9646-115a08a9907e.png)
